version: "3.9"
services:
  postgresql:
    image: postgres
    container_name: postgresql1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"