# See https://github.com/GaetanoPiazzolla/smart-document-assistant/tree/master
version: "3.9"

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'