# See https://medium.com/dandelion-tutorials/url-shortener-using-spring-boot-webflux-with-spring-data-and-reactive-redis-8b89f5e63221
version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./script/000-schema.sql:/docker-entrypoint-initdb.d/000-schema.sql
      - ./script/001-data.sql:/docker-entrypoint-initdb.d/001-data.sql
    ports:
      - "5432:5432"
  
  pgadmin:
    # pgadmin : http://localhost:80
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
